### PR TITLE
TLS Support

### PR DESCRIPTION
**Pull request by paralainer**
Another attempt to add TLS support.
Since last attempt:
* Merged with master
* Removed some redundant connection close code
* Changed approach to integration tests, useTls is now just a parameter for it.
* Ran pipeline multiple times on Github Actions, it didn't fail even once

### CODE REVIEW

**Comment by paralainer** [comment]
@thiagocesarj hopefully this time it won't cause any issues with tests

**Review by thiagocesarj — APPROVED** [review]

**Comment by thiagocesarj** [comment]
@paralainer thank you for the contribution! I will prepare a release for this feature as version 1.18.0.

**Comment by thiagocesarj** [comment]
We had another [error](https://github.com/spotify/folsom/actions/runs/6850270319/job/18624105823#step:4:1641).

**Comment by thiagocesarj** [comment]
This error doesn't make a lot of sense to me. It is essentially complaining that the handler in the pipeline did not handle the exception. But the change you've made puts SSL in the middle, and it not the last handler in the pipeline.

Also, it seems to happen only when building for master, but not when building for branch. This is a bit mysterious as well.

**Comment by paralainer** [comment]
Oh, I'll have a look into the error, I'm pretty sure it's some problem with test setup, we use that code in prod for a couple of months now in a high load service with no issues

**Pull request merged**
