### PR TITLE
Bump Guava to 19.0

### PR DESCRIPTION
**Pull request by odsod**
Compatible with Guava up to 21.0

@protocol7 @spkrka

### CODE REVIEW

**Comment by protocol7** [comment]
+1

**Comment by Evkin** [comment]
Super! Update version folsom (to 0.7.3) is planned?

**Comment by protocol7** [comment]
@Evkin 0.7.3 has been released now, might take to some time to replicate everywhere

**Comment by Evkin** [comment]
:+1:

**Pull request merged**
