### PR TITLE
Improve ttl logic

### PR DESCRIPTION
**Pull request by spkrka**

### CODE REVIEW

**Comment by flozano** [comment]
This makes it consistent between ASCII and binary, but it won't fix the actual issue of timestamp not expiring when expected, right?

**Comment by spkrka** [comment]
It also avoids converting from `ttl` to an expiration timestamp when `ttl < 30 days` (for both binary and ascii) so I think it should help your usecase too.
Perhaps the issue was misalignment in clocks between your client and server? If so, using ttls should be more preferable than timestamps.

**Comment by flozano** [comment]
Actually the server and the client are in the same laptop in the cases it's failing, so I don't think it's due to misalignment at all...

**Comment by protocol7** [comment]
+1, but maybe add a test for Utils

**Comment by spkrka** [comment]
Added some tests!

**Comment by spkrka** [comment]
@flozano yes, but perhaps your memcached server computes local time in seconds differently compared to how folsom does it in some way? One of them could be UTC, other one local timezone, or something similar.

Regardless, I think it's safer to send the expiration as TTL in seconds instead of as a timestamp.

**Comment by flozano** [comment]
I agree that fixing the TTL inconsistency for the binary protocol is a good idea, thanks for the effort, the improvement in this PR is good overall.

I just wonder why it fails with timestamps. In my opinion, the original issue should be kept open - or a new, more specific one if you prefer - as I think the behaviour we're seeing is really unexpected.

With regard to timestamp offset, I think timestamps are number of seconds since Jan 1st 1970 00:00:00 UTC everywhere, timestamp should not influence...

**Comment by spkrka** [comment]
Yes, once this is released, could you try to find some memcached docker image that can reproduce the problem? The existing new test case should hopefully be able to catch it.

If the problem only triggers when sending the expiration as a timestamp it would be harder to verify as you would need to have a test that waits for 30 days...

**Comment by jorcasso** [comment]
Why is this conversion needed?
```
int expirationTime = (int) (System.currentTimeMillis() / 1000) + ttl;
```
If `ttl >= TTL_CUTOFF`, does not mean that `ttl` should be treated as Unix time?

**Comment by spkrka** [comment]
According to the regular Memcached API, yes.
The Folsom API however, specifies it should be TTL in seconds.

**Comment by jorcasso** [comment]
I see, that makes sense then. Thanks.

**Comment by flozano** [comment]
Actually now this issue is almost un-testable for the original issue, as you said... It only happens with timestamp, so ... now I need to wait for 30 days for this to happen?

**Comment by spkrka** [comment]
I'll think some more about this. Some ideas are:
* Add a separate API to trigger this type of expiration
* Make the cutoff configurable somehow
* Add tests that modify the system clock of the memcached container (not sure how easy this would be)

Though overall, do you need to test it? 30 days cache TTL is quite long and I can't think of any usecases with higher TTLs.
If you have such a usecase, it may be worth following up on, but if you don't, perhaps we can leave it for now.

**Pull request merged**
