### PR TITLE
[relates #81] Fix InnoDB/memcached key length issue.

### PR DESCRIPTION
**Pull request by jludvice**

### CODE REVIEW

**Comment by danielnorberg** [comment]
How about making the key length limit configurable instead?

**Comment by jludvice** [comment]
Hi Daniel, great idea.
Would you be ok with l loading from system property with default to current 250?

**Comment by protocol7** [comment]
@danielnorberg what we're trying to guard against here is the max length allowed by memcached (https://github.com/memcached/memcached/blob/master/memcached.h#L30) right, would it make sense to make this configurable in Folsom?

**Comment by jludvice** [comment]
@protocol7 we hit issue with MySQL / InnoDB / Memcached where it allows max lenght 249.
I put code snippets in #81. Our MySQL actually went down due to high volume of messages with too long key (250).

**Comment by protocol7** [comment]
@jludvice oh sorry, my bad, I read the patch the wrong way. That's indeed an interesting and annoying bug. It would be nice if we worked out of the box with any memcache implementation, but I would tend to agree with @danielnorberg then that this should be configurable.

**Comment by spkrka** [comment]
I made an alternative PR to make this configurable. See https://github.com/spotify/folsom/pull/83

**Comment by jludvice** [comment]
I didn't dare to change so many lines in project I don't know. Your PR #83 works fine for me.

Here is one detail I missed in the original description.
Just 250 long key works fine with mysql - it get's truncated.
The ugly things happen to keys like this
```java
MemcacheClient<String> client = MemcacheClientBuilder.newStringClient()
                .withAddress(HostAndPort.fromString("localhost:11211"))
//                .withMaxKeyLength(249)
                .connectAscii();

String key = "@@FFFFFF_FFFFFFFFFFFFFF.EEE-RRRRRRRR.AAAAA.com/json/rn7837/fp915226557/pr2/re/ur0068007400740070003a002f002f006d002e006b006e00610063006b002e00620065002f006e00690065007500770073002f/brSafari;Safariundefined;iOS;phone/dephone/dtphone/?t=1487612233852";

System.out.println(client.get(key).get());
```
The `@@FFF...` refers to `@@table_id` notation described here
https://dev.mysql.com/doc/refman/5.7/en/innodb-memcached-intro.html


Calling get for this key caused MySQL restart :D
```
java.util.concurrent.ExecutionException: com.spotify.folsom.MemcacheClosedException: Disconnected

	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.spotify.folsom.WndTest.test(WndTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.spotify.folsom.MemcacheClosedException: Disconnected
	at com.spotify.folsom.client.DefaultRawMemcacheClient$ConnectionHandler.channelInactive(DefaultRawMemcacheClient.java:323)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:240)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:379)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:344)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:240)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1289)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:240)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:226)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:893)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:690)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:399)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

I'm +1 for #83 in favour of this PR.

Do you have any ETA for next folsom release ? 

Thank you for such quick response.
Josef

**Comment by jludvice** [comment]
Closing this PR in favour of #83.

**Pull request closed without merging**
